# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- azure-pipelines-001
  
pool:
  vmImage: windows-2019

steps:
  
- script:  choco install ruby --version=3.1.5.1

  displayName: Install Jekyll and bundler
- script: |
    gem install jekyll bundler
 
  displayName: Install Gems
- script: 
     bundle update --bundler
     bundle install

  displayName: Build
- script: 'bundle exec jekyll build'
